#!/usr/bin/env bash
#
# Amalgamation step: turn the real, compilable runtime fragments in src/runtime/*.hpp
# into a single embedded header of raw-string constants that the compiler bakes in,
# so generated binaries stay self-contained while the runtime source stays real C++.
#
#   tools/embed_runtime.sh <out.hpp> <runtime1.hpp> [runtime2.hpp ...]
#
# Each src/runtime/<name>.hpp becomes:  static const char* RT_<NAME> = R"HEXRT(...)HEXRT";
# Raw string literals preserve bytes verbatim, so codegen output is unchanged.

set -eu

OUT="$1"; shift

{
    echo "// AUTO-GENERATED by tools/embed_runtime.sh from src/runtime/*.hpp — do not edit."
    echo "#pragma once"
    for f in "$@"; do
        base="$(basename "$f" .hpp)"
        name="$(printf '%s' "$base" | tr '[:lower:]-' '[:upper:]_')"
        printf 'static const char* RT_%s = R"HEXRT(' "$name"
        cat "$f"
        printf ')HEXRT";\n'
    done
} > "$OUT"
